language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
env:
  - SYMFONY_CONSOLE_VERSION=2.8.*
  - SYMFONY_CONSOLE_VERSION=3.*
matrix:
  include:
    - php: 7.1
      env: SYMFONY_CONSOLE_VERSION=4.*
    - php: 7.2
      env: SYMFONY_CONSOLE_VERSION=4.*

install:
  - composer require symfony/console:${SYMFONY_CONSOLE_VERSION}
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

